version: "3.7"

services:
  lemmy:
    image: dessalines/lemmy:0.19.7
    restart: always
    networks:
     - default
     - terminator
    volumes:
      - ./lemmy.hjson:/config/config.hjson:Z
    env_file:
     - .env
    depends_on:
      - postgres
      - pictrs
    labels:
      - "promtail=true"

  lemmy-ui:
    image: dessalines/lemmy-ui:0.19.5
    restart: always
    networks:
     - default
     - terminator
    volumes:
      - ./extra_themes:/app/extra_themes
    depends_on:
      - lemmy
    environment:
     LEMMY_UI_LEMMY_INTERNAL_HOST: lemmy:8536
     LEMMY_UI_CUSTOM_HTML_HEADER: "<script src=\"/oauth-login/assets/oauth-button.js\"></script>"
    labels:
      - "promtail=true"

  pictrs:
    image: asonix/pictrs:0.5.16
    restart: always
    user: 991:991
    networks:
     - default
     - terminator
    volumes:
      - ./data/pictrs:/mnt:Z
    labels:
      - "promtail=true"

  postgres:
    image: postgres:16.2
    env_file:
     - .env
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    restart: always
    labels:
      - "promtail=true"

  oauth_companion:
    image: ghcr.io/minetest-ch/lemmy-oauth-companion:1.0.4
    environment:
      LEMMY_URL: "http://lemmy:8536"
      BASE_URL: "https://lemmy.minetest.ch"
      COOKIE_SECURE: "true"
    env_file:
     - .env
    depends_on:
     - postgres
     - lemmy
    restart: always
    labels:
      - "promtail=true"

  lemmy-nginx:
    image: nginx:1.27.1
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro,Z"
      - "./assets:/assets"
      - "./proxy_params:/etc/nginx/proxy_params:ro,Z"
    networks:
     - default
     - terminator
    restart: always
    depends_on:
      - pictrs
      - lemmy-ui
    labels:
      - "promtail=true"
      - "traefik.enable=true"
      - "traefik.docker.network=terminator"
      - "traefik.http.routers.lemmy-minetest-ch.rule=Host(`lemmy.minetest.ch`)"
      - "traefik.http.services.lemmy-minetest-ch.loadbalancer.server.port=8536"
      - "traefik.http.routers.lemmy-minetest-ch.entrypoints=websecure"
      - "traefik.http.routers.lemmy-minetest-ch.tls.certresolver=default"

networks:
 terminator:
  external: true
