name: validate

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: validate config
      run: |
        touch .env
        docker-compose config -q
        docker-compose pull
